apiVersion: apps/v1
kind: Deployment
metadata:
  name: re-platform-peerserver-dev
  labels:
    app: re-platform-peerserver-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: re-platform-peerserver-dev
  template:
    metadata:
      labels:
        project: re-platform-peerserver-dev
    spec:
      containers:
        - name: re-platform-peerserver
          image: asiman61/re-platform-peerserver-dev:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: re-platform-peerserver-dev
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: re-platform-peerserver-dev
  ports:
    - name: re-platform-peerserver
      protocol: TCP
      nodePort: 30952
      port: 3000 # port on load balancer
      targetPort: 3000 # port on pod
  type: LoadBalancer
